import base58 # pip install base58
import hashlib
import argparse

CONFIG={ 
    "2GIVE":{"networkVersion":b'\x27',"privateKeyPrefix":b'\xa7', "privateKeyBase58Start":"6"},
    "42coin":{"networkVersion":b'\x08',"privateKeyPrefix":b'\x88', "privateKeyBase58Start":"5"},
    "Acoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\xe6', "privateKeyBase58Start":"8"},
    "AGAcoin":{"networkVersion":b'\x53',"privateKeyPrefix":b'\xd3', "privateKeyBase58Start":"8"},
    "Alphacoin":{"networkVersion":b'\x52',"privateKeyPrefix":b'\xd2', "privateKeyBase58Start":"8"},
    "Alqo":{"networkVersion":b'\x17',"privateKeyPrefix":b'\xc1', "privateKeyBase58Start":"7"},
    "Animecoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "Anoncoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "Apexcoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "Auroracoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "Aquariuscoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "Axe":{"networkVersion":b'\x4B',"privateKeyPrefix":b'\xCB', "privateKeyBase58Start":"7"},
    "BBQcoin":{"networkVersion":b'\x55',"privateKeyPrefix":b'\xd5', "privateKeyBase58Start":"6"},
    "Biblepay":{"networkVersion":b'\x19',"privateKeyPrefix":b'\xb6', "privateKeyBase58Start":"7"},
    "Bitcoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "BitcoinCash":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "BitcoinDark":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "Bitcore":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "BitcoinGold":{"networkVersion":b'\x26',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Bitconnect":{"networkVersion":b'\x12',"privateKeyPrefix":b'\x92', "privateKeyBase58Start":"5"},
    "Birdcoin":{"networkVersion":b'\x2f',"privateKeyPrefix":b'\xaf', "privateKeyBase58Start":"6"},
    "BitSynq":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "BitZeny":{"networkVersion":b'\x51',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Blackcoin":{"networkVersion":b'\x19',"privateKeyPrefix":b'\x99', "privateKeyBase58Start":"6"},
    "BlackJack":{"networkVersion":b'\x15',"privateKeyPrefix":b'\x95', "privateKeyBase58Start":"6"},
    "BlockNet":{"networkVersion":b'\x1a',"privateKeyPrefix":b'\x9a', "privateKeyBase58Start":"6"},
    "BolivarCoin":{"networkVersion":b'\x55',"privateKeyPrefix":b'\xd5', "privateKeyBase58Start":"8"},
    "BoxyCoin":{"networkVersion":b'\x4b',"privateKeyPrefix":b'\xcb', "privateKeyBase58Start":"7"},
    "BunnyCoin":{"networkVersion":b'\x1a',"privateKeyPrefix":b'\x9a', "privateKeyBase58Start":"6"},
    "Cagecoin":{"networkVersion":b'\x1f',"privateKeyPrefix":b'\x9f', "privateKeyBase58Start":"6"},
    "CampusCoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "CanadaeCoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "CannabisCoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "Capricoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "CassubianDetk":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "CashCoin":{"networkVersion":b'\x22',"privateKeyPrefix":b'\xa2', "privateKeyBase58Start":"6"},
    "Catcoin":{"networkVersion":b'\x15',"privateKeyPrefix":b'\x95', "privateKeyBase58Start":"6"},
    "ChainCoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "ColossusCoinXT":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\xd4', "privateKeyBase58Start":"5"},
    "Condensate":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "Copico":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x90', "privateKeyBase58Start":"5"},
    "CopperCoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "Corgicoin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "CryptoBullion":{"networkVersion":b'\x0b',"privateKeyPrefix":b'\x8b', "privateKeyBase58Start":"5"},
    "CryptoClub":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xa3', "privateKeyBase58Start":"6"},
    "Cryptoescudo":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "Cryptonite":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "CryptoWisdomCoin":{"networkVersion":b'\x49',"privateKeyPrefix":b'\x87', "privateKeyBase58Start":"5"},
    "C2coin":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x9c', "privateKeyBase58Start":"6"},
    "Dash":{"networkVersion":b'\x4c',"privateKeyPrefix":b'\xcc', "privateKeyBase58Start":"7"},
    "DeafDollars":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "DeepOnion":{"networkVersion":b'\x1f',"privateKeyPrefix":b'\x9f', "privateKeyBase58Start":"6"},
    "Deutsche eMark":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb5', "privateKeyBase58Start":"7"},
    "Devcoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "DigiByte":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "Digitalcoin":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "Dimecoin":{"networkVersion":b'\x0f',"privateKeyPrefix":b'\x8f', "privateKeyBase58Start":"5"},
    "DNotes":{"networkVersion":b'\x1f',"privateKeyPrefix":b'\x9f', "privateKeyBase58Start":"6"},
    "Dogecoin":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "DogecoinDark":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "eGulden":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "eKrona":{"networkVersion":b'\x2d',"privateKeyPrefix":b'\xad', "privateKeyBase58Start":"6"},
    "ELECTRA":{"networkVersion":b'\x21',"privateKeyPrefix":b'\xa1', "privateKeyBase58Start":"6"},
    "Ember":{"networkVersion":b'\x5c',"privateKeyPrefix":b'\x32', "privateKeyBase58Start":"2"},
    "Emerald":{"networkVersion":b'\x22',"privateKeyPrefix":b'\xa2', "privateKeyBase58Start":"6"},
    "Emercoin":{"networkVersion":b'\x21',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "EnergyCoin":{"networkVersion":b'\x5c',"privateKeyPrefix":b'\xdc', "privateKeyBase58Start":"8"},
    "Espers":{"networkVersion":b'\x21',"privateKeyPrefix":b'\x90', "privateKeyBase58Start":"5"},
    "Fastcoin":{"networkVersion":b'\x60',"privateKeyPrefix":b'\xe0', "privateKeyBase58Start":"8"},
    "Feathercoin":{"networkVersion":b'\x0e',"privateKeyPrefix":b'\x8e', "privateKeyBase58Start":"5"},
    "Fedoracoin":{"networkVersion":b'\x21',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Fibre":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xa3', "privateKeyBase58Start":"6"},
    "Florincoin":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "Flurbo":{"networkVersion":b'\x23',"privateKeyPrefix":b'\x30', "privateKeyBase58Start":"6"},
    "Fluttercoin":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xa3', "privateKeyBase58Start":"6"},
    "FrazCoin":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xA3', "privateKeyBase58Start":"6"},
    "Freicoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "FUDcoin":{"networkVersion":b'\x23',"privateKeyPrefix":b'\xa3', "privateKeyBase58Start":"6"},
    "Fuelcoin":{"networkVersion":b'\x24',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Fujicoin":{"networkVersion":b'\x24',"privateKeyPrefix":b'\xa4', "privateKeyBase58Start":"6"},
    "GabenCoin":{"networkVersion":b'\x10',"privateKeyPrefix":b'\x90', "privateKeyBase58Start":"5"},
    "Garlicoin":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "GlobalBoost":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xa6', "privateKeyBase58Start":"6"},
    "Goodcoin":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xa6', "privateKeyBase58Start":"6"},
    "GridcoinResearch":{"networkVersion":b'\x3e',"privateKeyPrefix":b'\xbe', "privateKeyBase58Start":"7"},
    "Gulden":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xa6', "privateKeyBase58Start":"6"},
    "Guncoin":{"networkVersion":b'\x27',"privateKeyPrefix":b'\xa7', "privateKeyBase58Start":"6"},
    "HamRadioCoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "HFRcoin":{"networkVersion":b'\x10',"privateKeyPrefix":b'\x90', "privateKeyBase58Start":"5"},
    "HOdlcoin":{"networkVersion":b'\x28',"privateKeyPrefix":b'\xa8', "privateKeyBase58Start":"5"},
    "HTMLCoin":{"networkVersion":b'\x29',"privateKeyPrefix":b'\xa9', "privateKeyBase58Start":"6"},
    "HyperStake":{"networkVersion":b'\x75',"privateKeyPrefix":b'\xf5', "privateKeyBase58Start":"9"},
    "ImperiumCoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "IncaKoin":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb5', "privateKeyBase58Start":"7"},
    "IncognitoCoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Influxcoin":{"networkVersion":b'\x66',"privateKeyPrefix":b'\xe6', "privateKeyBase58Start":"8"},
    "Innox":{"networkVersion":b'\x4b',"privateKeyPrefix":b'\xcb', "privateKeyBase58Start":"7"},
    "IridiumCoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "iCash":{"networkVersion":b'\x66',"privateKeyPrefix":b'\xcc', "privateKeyBase58Start":"7"},
    "iXcoin":{"networkVersion":b'\x8a',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Judgecoin":{"networkVersion":b'\x2b',"privateKeyPrefix":b'\xab', "privateKeyBase58Start":"6"},
    "Jumbucks":{"networkVersion":b'\x2b',"privateKeyPrefix":b'\xab', "privateKeyBase58Start":"6"},
    "KHcoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "KittehCoin":{"networkVersion":b'\x2d',"privateKeyPrefix":b'\xad', "privateKeyBase58Start":"6"},
    "Lanacoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "Latium":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "LBRY Credits":{"networkVersion":b'\x55',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Litecoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "LiteDoge":{"networkVersion":b'\x5a',"privateKeyPrefix":b'\xab', "privateKeyBase58Start":"6"},
    "LoMoCoin":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "MadbyteCoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\x6e', "privateKeyBase58Start":"4"},
    "MagicInternetMoney":{"networkVersion":b'\x30',"privateKeyPrefix":b'\xb0', "privateKeyBase58Start":"6"},
    "Magicoin":{"networkVersion":b'\x14',"privateKeyPrefix":b'\x94', "privateKeyBase58Start":"5"},
    "Marscoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "MarteXcoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "MasterDoge":{"networkVersion":b'\x33',"privateKeyPrefix":b'\x8b', "privateKeyBase58Start":"5"},
    "Mazacoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xe0', "privateKeyBase58Start":"8"},
    "Megacoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "MintCoin":{"networkVersion":b'\x33',"privateKeyPrefix":b'\xb3', "privateKeyBase58Start":"7"},
    "MobiusCoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "MonetaryUnit":{"networkVersion":b'\x10',"privateKeyPrefix":b'\x7e', "privateKeyBase58Start":"5"},
    "Monocle":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "MoonCoin":{"networkVersion":b'\x03',"privateKeyPrefix":b'\x83', "privateKeyBase58Start":"5"},
    "Myriadcoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "NameCoin":{"networkVersion":b'\x34',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Navcoin":{"networkVersion":b'\x35',"privateKeyPrefix":b'\x96', "privateKeyBase58Start":"6"},
    "NeedleCoin":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb5', "privateKeyBase58Start":"7"},
    "NEETCOIN":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb5', "privateKeyBase58Start":"7"},
    "NYC":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "Neoscoin":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb1', "privateKeyBase58Start":"6"},
    "Nevacoin":{"networkVersion":b'\x35',"privateKeyPrefix":b'\xb1', "privateKeyBase58Start":"6"},
    "Novacoin":{"networkVersion":b'\x08',"privateKeyPrefix":b'\x88', "privateKeyBase58Start":"5"},
    "Nubits":{"networkVersion":b'\x19',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "Nyancoin":{"networkVersion":b'\x2d',"privateKeyPrefix":b'\xad', "privateKeyBase58Start":"6"},
    "Ocupy":{"networkVersion":b'\x73',"privateKeyPrefix":b'\xf3', "privateKeyBase58Start":"9"},
    "Omnicoin":{"networkVersion":b'\x73',"privateKeyPrefix":b'\xf3', "privateKeyBase58Start":"9"},
    "Onyxcoin":{"networkVersion":b'\x73',"privateKeyPrefix":b'\xf3', "privateKeyBase58Start":"9"},
    "PacCoin":{"networkVersion":b'\x18',"privateKeyPrefix":b'\x98', "privateKeyBase58Start":"6"},
    "Particl":{"networkVersion":b'\x38',"privateKeyPrefix":b'\x6c', "privateKeyBase58Start":"4"},
    "Paycoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "Pandacoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "ParkByte":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "Peercoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "Pesetacoin":{"networkVersion":b'\x2f',"privateKeyPrefix":b'\xaf', "privateKeyBase58Start":"6"},
    "PHCoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "PhoenixCoin":{"networkVersion":b'\x38',"privateKeyPrefix":b'\xb8', "privateKeyBase58Start":"7"},
    "PiggyCoin":{"networkVersion":b'\x76',"privateKeyPrefix":b'\xf6', "privateKeyBase58Start":"9"},
    "PIVX":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\xd4', "privateKeyBase58Start":"8"},
    "Peercoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "Potcoin":{"networkVersion":b'\x37',"privateKeyPrefix":b'\xb7', "privateKeyBase58Start":"7"},
    "Primecoin":{"networkVersion":b'\x17',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "ProsperCoinClassic":{"networkVersion":b'\x3a',"privateKeyPrefix":b'\xba', "privateKeyBase58Start":"7"},
    "Quark":{"networkVersion":b'\x3a',"privateKeyPrefix":b'\xba', "privateKeyBase58Start":"7"},
    "Qubitcoin":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xe0', "privateKeyBase58Start":"8"},
    "Reddcoin":{"networkVersion":b'\x3d',"privateKeyPrefix":b'\xbd', "privateKeyBase58Start":"7"},
    "Riecoin":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Rimbit":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "ROIcoin":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Rubycoin":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "Rupaya":{"networkVersion":b'\x3c',"privateKeyPrefix":b'\xbc', "privateKeyBase58Start":"7"},
    "Sambacoin":{"networkVersion":b'\x3e',"privateKeyPrefix":b'\xbe', "privateKeyBase58Start":"7"},
    "SecKCoin":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "SibCoin":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "SixEleven":{"networkVersion":b'\x34',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "SmileyCoin":{"networkVersion":b'\x19',"privateKeyPrefix":b'\x99', "privateKeyBase58Start":"6"},
    "SongCoin":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "SpreadCoin":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "StealthCoin":{"networkVersion":b'\x3e',"privateKeyPrefix":b'\xbe', "privateKeyBase58Start":"7"},
    "Stratis":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\xbf', "privateKeyBase58Start":"7"},
    "SwagBucks":{"networkVersion":b'\x3f',"privateKeyPrefix":b'\x99', "privateKeyBase58Start":"6"},
    "Syscoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Tajcoin":{"networkVersion":b'\x41',"privateKeyPrefix":b'\x6f', "privateKeyBase58Start":"6"},
    "Terracoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Titcoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "TittieCoin":{"networkVersion":b'\x41',"privateKeyPrefix":b'\xc1', "privateKeyBase58Start":"7"},
    "Topcoin":{"networkVersion":b'\x42',"privateKeyPrefix":b'\xc2', "privateKeyBase58Start":"7"},
    "TransferCoin":{"networkVersion":b'\x42',"privateKeyPrefix":b'\x99', "privateKeyBase58Start":"6"},
    "TreasureHuntCoin":{"networkVersion":b'\x32',"privateKeyPrefix":b'\xb2', "privateKeyBase58Start":"6"},
    "TrezarCoin":{"networkVersion":b'\x42',"privateKeyPrefix":b'\xC2', "privateKeyBase58Start":"7"},
    "Unobtanium":{"networkVersion":b'\x82',"privateKeyPrefix":b'\xe0', "privateKeyBase58Start":"8"},
    "USDe":{"networkVersion":b'\x26',"privateKeyPrefix":b'\xa6', "privateKeyBase58Start":"6"},
    "Vcash":{"networkVersion":b'\x47',"privateKeyPrefix":b'\xc7', "privateKeyBase58Start":"7"},
    "Versioncoin":{"networkVersion":b'\x46',"privateKeyPrefix":b'\xc6', "privateKeyBase58Start":"7"},
    "VergeCoin":{"networkVersion":b'\x1e',"privateKeyPrefix":b'\x9e', "privateKeyBase58Start":"6"},
    "Vertcoin":{"networkVersion":b'\x47',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Viacoin":{"networkVersion":b'\x47',"privateKeyPrefix":b'\xc7', "privateKeyBase58Start":"7"},
    "VikingCoin":{"networkVersion":b'\x46',"privateKeyPrefix":b'\x56', "privateKeyBase58Start":"3"},
    "W2Coin":{"networkVersion":b'\x49',"privateKeyPrefix":b'\xc9', "privateKeyBase58Start":"7"},
    "WACoins":{"networkVersion":b'\x49',"privateKeyPrefix":b'\xc9', "privateKeyBase58Start":"7"},
    "WankCoin":{"networkVersion":b'\x00',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "WeAreSatoshiCoin":{"networkVersion":b'\x87',"privateKeyPrefix":b'\x97', "privateKeyBase58Start":"6"},
    "WorldCoin":{"networkVersion":b'\x49',"privateKeyPrefix":b'\xc9', "privateKeyBase58Start":"7"},
    "XP":{"networkVersion":b'\x4b',"privateKeyPrefix":b'\xcb', "privateKeyBase58Start":"7"},
    "Yenten":{"networkVersion":b'\x4e',"privateKeyPrefix":b'\x7b', "privateKeyBase58Start":"5"},
    "Zcash":{"networkVersion":b'\x1c',"privateKeyPrefix":b'\x80', "privateKeyBase58Start":"5"},
    "Zetacoin":{"networkVersion":b'\x50',"privateKeyPrefix":b'\xE0', "privateKeyBase58Start":"8"}
}
def encodePrivateKey(network, hexPrivateKey):
    # 将十六进制私钥解码为字节数据
    bytesPrivateKey = bytes.fromhex(hexPrivateKey)

    # 添加前缀字节（通常为\x80）
    bytesPrivateKeyPrefixed = CONFIG[network]['privateKeyPrefix'] + bytesPrivateKey

    # 计算校验和
    checksum = hashlib.sha256(hashlib.sha256(bytesPrivateKeyPrefixed).digest()).digest()[:4]

    # 添加校验和
    bytesPrivateKeyPrefixedChecksum = bytesPrivateKeyPrefixed + checksum

    # Base58编码
    base58PrivateKey = base58.b58encode(bytesPrivateKeyPrefixedChecksum)

    print("Base58格式私钥：", base58PrivateKey.decode())

if __name__ == '__main__':

    ap = argparse.ArgumentParser()
    ap.add_argument('-hex', default=None, required=True, help='A hex private key, which length is 64')
    ap.add_argument('-network', default=None, required=True, help='Chain')
    args = ap.parse_args()
    encodePrivateKey(args.network, args.hex)
    
